spring.data.mongodb.database=${env.DATABASE_NAME}
spring.data.mongodb.uri=${env.MONGO_URI}
server.port=7200
#server.ssl.key-store = classpath:keystore.jks
#server.ssl.key-store-password = yourpassword
#server.ssl.key-password = yourpassword
#server.ssl.keyStoreType = JKS
#server.ssl.keyAlias = selfsigned